name: music_logger_app
description: A personal music journaling and tracking app.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1    # state management
  hive_flutter: ^1.1.0        # local storage
  http: ^1.2.1                # API calls
  cached_network_image: ^3.3.1 # image caching
  go_router: ^17.2.2          # navigation / routing
  youtube_player_flutter: ^9.0.3
  url_launcher: ^6.2.6        # open external links
  flutter_dotenv: ^6.0.1      # API key management
  intl: ^0.20.2               # date / number formatting
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
  fonts: []
    # Add custom fonts here:
    # - family: MyFont
    #   fonts:
    #     - asset: assets/fonts/MyFont-Regular.ttf
